### ISSUE TITLE
i am using library for project with react native version 0.60.4 .For me login by phone is success but when i using getCurrentAccount function then result of promise is {} ., no property?

### ISSUE THREAD

**Issue by truongcoino1** [underscopeio/react-native-facebook-account-kit#204] opened 2019-08-24 06:44 UTC
## Hey there! Please follow the steps described below

Before submit a new issue be sure about the following points

- [ ] You're using the latest release of this module: https://github.com/underscopeio/react-native-facebook-account-kit/releases

- [ ] You've searched through existing issues: https://github.com/underscopeio/react-native-facebook-account-kit/issues and the issue is not already reported.

- [ ] You have filled out the template below, or provided an equivalent amount of detail.

Describe your issue in as much detail as possible. Provide **screenshots** where appropriate. Provide a **minimal code snippet** or include a list of detailed list of steps that reproduce the issue.

--- delete everything above this line before submitting your issue ---

### Issue Description

[FILL THIS OUT]

### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native Account Kit version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* Platform Version(s): [FILL THIS OUT]

**Comment by jpgarcia** [comment] 2019-08-31 23:56
Hi @truongcoino1 I'm closing this issue as I could not reproduce it.

I've created a sample from scratch and it worked.

Please try out the following code and let me know if it works:

```jsx
import React, {Fragment, useEffect} from 'react';
import {Alert, SafeAreaView, Button} from 'react-native';

import RNAccountKit from 'react-native-facebook-account-kit';

const App = () => {
  useEffect(() => {
    RNAccountKit.configure({responseType: 'token'});
  }, []);

  async function handleLoginWithPhone() {
    try {
      const accessToken = await RNAccountKit.loginWithPhone();

      if (accessToken) {
        Alert.alert('Access Token', accessToken);
      } else {
        Alert.alert('Login cancelled', 'Login was cancelled');
      }
    } catch (err) {
      Alert.alert('Error', err.message);
    }
  }

  async function handleLoginWithEmail() {
    try {
      const accessToken = await RNAccountKit.loginWithEmail();

      if (accessToken) {
        Alert.alert('Access Token', accessToken);
      } else {
        Alert.alert('Login cancelled', 'Login was cancelled');
      }
    } catch (err) {
      Alert.alert('Error', err.message);
    }
  }

  async function handleShowAccessToken() {
    try {
      let accessToken = await RNAccountKit.getCurrentAccessToken();
      Alert.alert('Access Token', accessToken ? accessToken : 'Token is empty');
    } catch (err) {
      Alert.alert('Error', err.message);
    }
  }

  async function handleShowAccount() {
    try {
      let account = await RNAccountKit.getCurrentAccount();
      Alert.alert('Account', account);
    } catch (err) {
      Alert.alert('Error', err.message);
    }
  }

  async function handleLogout() {
    try {
      await RNAccountKit.logout();
    } catch (err) {
      Alert.alert('Error', err.message);
    }
  }

  return (
    <Fragment>
      <SafeAreaView>
        <Button title="Login with Phone" onPress={handleLoginWithPhone} />
        <Button title="Login with Email" onPress={handleLoginWithEmail} />
        <Button title="Show Access Token" onPress={handleShowAccessToken} />
        <Button title="Show Account" onPress={handleShowAccount} />
        <Button title="Logout" onPress={handleLogout} />
      </SafeAreaView>
    </Fragment>
  );
};

export default App;

```

**Closed by jpgarcia** 2019-08-31 23:56 UTC

**Comment by truongcoino1** [comment] 2019-09-06 02:13
yep, thank you support for me.
