### ISSUE TITLE
Crash when open Accountkit Android

### ISSUE THREAD

**Issue by duongnv1996** [underscopeio/react-native-facebook-account-kit#53] opened 2016-11-08 19:17 UTC
### Issue Description

Hello . I received this logcat from user , when try to open Account kit via intent .

java.lang.NullPointerException
1	at com.facebook.accountkit.internal.AppEventsLogger.handleResponse(AppEventsLogger.java:526)
2	at com.facebook.accountkit.internal.AppEventsLogger.access$600(AppEventsLogger.java:57)
3	at com.facebook.accountkit.internal.AppEventsLogger$4.onCompleted(AppEventsLogger.java:510)
4	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:188)
5	at com.facebook.accountkit.internal.AccountKitGraphRequestAsyncTask.onPostExecute(AccountKitGraphRequestAsyncTask.java:42)
6	at android.os.AsyncTask.finish(AsyncTask.java:631)
7	at android.os.AsyncTask.access$600(AsyncTask.java:177)
8	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
9	at android.os.Handler.dispatchMessage(Handler.java:99)
10	at android.os.Looper.loop(Looper.java:137)
11	at android.app.ActivityThread.main(ActivityThread.java:5041)
12	at java.lang.reflect.Method.invokeNative(Native Method)
13	at java.lang.reflect.Method.invoke(Method.java:511)
14	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
15	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
16	at dalvik.system.NativeStart.main(Native Method)

* React Native Account Kit version: 4+

* Platform(s) (iOS, Android, or both?): Android

Need some feedback from you,please!

Thank alot!

**Comment by gaguirre** [comment] 2016-11-14 18:01
This is a duplicate of #52 
Please reopen if i'm wrong!

**Closed by gaguirre** 2016-11-14 18:01 UTC
