### ISSUE TITLE
Android build error 

### ISSUE THREAD

**Issue by Desintegrator** [underscopeio/react-native-facebook-account-kit#159] opened 2018-10-22 08:38 UTC
### Issue Description

Can't run application with latest release of account kit on Android

This is what i get: 

* Where:
Build file 'path-to-node-modules/node_modules/react-native-facebook-account-kit/android/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':react-native-facebook-account-kit'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### Steps to Reproduce / Code Snippets

1. run './gradlew installDebug' or './gradlew assembleRelease'

#### Expected Results

App should be installed

### Additional Information

* React Native Account Kit version: 1.0.0
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by MrLich** [comment] 2018-10-31 14:22
how about ios ??? I can not run on ios :(

**Comment by Desintegrator** [comment] 2018-10-31 14:32
> how about ios ??? I can not run on ios :(

I have no problem with ios
Leave your logs here

**Comment by jpgarcia** [comment] 2018-10-31 15:45
@Desintegrator I've just run:

```bash
react-native init sample-app --version  0.57.3
react-native add react-native-facebook-account-kit
react-native link react-native-facebook-account-kit
```
Then I followed the [Configuration steps](https://github.com/underscopeio/react-native-facebook-account-kit#configuration) described in the Readme and everything worked

It seems that the `Could not find method implementation()` error you are receiving is related to the gradle version. Please check the `android/build.gradle` file to see what version are you using. The default version for RN 0.53.7 is:

```gradle
classpath 'com.android.tools.build:gradle:3.1.4'
```

also check the `android/gradle/wrapper/gradle-wrapper.properties` which should be 

```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```
I'll close this as I could not reproduce it. Please let me know how it goes

**Closed by jpgarcia** 2018-10-31 15:45 UTC

**Comment by MrLich** [comment] 2018-11-01 01:45
I have done it after installing by cocoaspod :) thanks for your comments.

Vào Th 4, 31 thg 10, 2018 vào lúc 22:52 Juan Pablo Garcia Dalolla <
notifications@github.com> đã viết:

**Comment by dattran97** [comment] 2019-01-09 03:37
@jpgarcia I have followed all your steps but it still have error. I use react-native: 0.57.3 and facebook-account-kit: 1.0.1
```
> Task :react-native-facebook-account-kit:compileDebugJavaWithJavac FAILED
/Users/dat/Documents/Projects/Working/O2F/bravo-rn/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fb
ak/RNAccountKitModule.java:34: error: RNAccountKitModule is not abstract and does not override abstract method onActivityResult(int,int,Intent
) in ActivityEventListener
public class RNAccountKitModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/dat/Documents/Projects/Working/O2F/bravo-rn/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fb
ak/RNAccountKitModule.java:63: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/dat/Documents/Projects/Working/O2F/bravo-rn/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitPackage.java:14: error: RNAccountKitPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNAccountKitPackage implements ReactPackage {
       ^
Note: /Users/dat/Documents/Projects/Working/O2F/bravo-rn/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
```
