### ISSUE TITLE
Unable to start activity ComponentInfo{com.fetchsky.peekaboo/com.facebook.accountkit.ui.AccountKitActivity}

### ISSUE THREAD

**Issue by zsajjad** [underscopeio/react-native-facebook-account-kit#17] opened 2016-07-01 09:58 UTC
App is getting crashed randomly on this error.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fetchsky.peekaboo/com.facebook.accountkit.ui.AccountKitActivity}: 500: Initialization error: 501: The SDK has not been initialized, make sure to call AccountKit.initialize() first
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2771)
	at android.app.ActivityThread.access$900(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: 500: Initialization error: 501: The SDK has not been initialized, make sure to call AccountKit.initialize() first
	at com.facebook.accountkit.internal.Validate.sdkInitialized(Validate.java:82)
	at com.facebook.accountkit.internal.Initializer.getApplicationName(Initializer.java:191)
	at com.facebook.accountkit.internal.AccountKitController.getApplicationName(AccountKitController.java:584)
	at com.facebook.accountkit.AccountKit.getApplicationName(AccountKit.java:289)
	at com.facebook.accountkit.ui.AccountKitActivity.onCreate(AccountKitActivity.java:184)
	at android.app.Activity.performCreate(Activity.java:6185)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650)
	... 10 more
```

**Comment by gaguirre** [comment] 2016-07-01 12:45
Hi @zsajjad, make sure you have set the right credentials.
Does the sample project work on your machine?

**Comment by gaguirre** [comment] 2016-07-20 14:38
I'll close this. Re-open if necessary.

**Closed by gaguirre** 2016-07-20 14:38 UTC

**Comment by zsajjad** [comment] 2016-12-18 07:35
Yes i have right credentials set and sample project also works very fine!

**Comment by AiritAndroid** [comment] 2019-03-18 10:23
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2957)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6942)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: 500: 
  at com.facebook.accountkit.internal.Validate.sdkInitialized (Validate.java:82)
  at com.facebook.accountkit.internal.Initializer.getApplicationName (Initializer.java:193)
  at com.facebook.accountkit.internal.AccountKitController.getApplicationName (AccountKitController.java:630)
  at com.facebook.accountkit.AccountKit.getApplicationName (AccountKit.java:284)
  at com.facebook.accountkit.ui.AccountKitActivity.onCreate (AccountKitActivity.java:279)
  at android.app.Activity.performCreate (Activity.java:7183)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1221)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)
