### ISSUE TITLE
'Get a code on facebook' option not working

### ISSUE THREAD

**Issue by SAHITYASAI** [underscopeio/react-native-facebook-account-kit#182] opened 2019-04-04 02:48 UTC
I integrated react-native-facebook-account-kit and used the **loginWithPhone()** and **getCurrentAccount()** methods in a uber-like react native app. I entered my mobile number, choose the **didn't get a code** and **get a code on Facebook** options and waited for a day to **get a notification on my Facebook account** to which the entered mobile number is linked. **But didn't receive any notification.** I would like to know if any extra methods or procedures need to be followed to get the notification or **if its possible to hide the option** in my app.

> React Native version: 0.57.1
> react-native-facebook-account-kit version: 1.1.0

code snippet: Below is the snippet of the code i used in my app
```
 facebookLogin() {
      RNAccountKit.configure({
        theme: {
          // Button
          buttonBackgroundColor: Color.hex('#FF2929'),
          buttonBorderColor: Color.hex('#FF2929'),
          buttonTextColor: Color.hex('#fff'),
          // Header
          headerBackgroundColor: Color.rgba(255,41,41),
          // input
          inputTextColor: Color.hex('#FF2929'),
          // icon
          iconColor: Color.hex('#FF2929')
        }
      })
      RNAccountKit.loginWithPhone()
      .then((token) => {
        this.setState({
          token: token
        })
          if (!token) {
            Alert.alert(
              "UrbanRider",
              "Please Login Again",
              [{ text: "OK", onPress: () => this.facebookLogin() }],
              { cancelable: false }
            );
          } else {
          AccountKit.getCurrentAccount().then(account => {
            console.log(`Token:hjjkhjkhjkh ${JSON.stringify(account)}`);
             this.setState({
             loggedAccount: account.phoneNumber
             }, () => {
               this.onFacebookLogin(account.phoneNumber)
             });         
             //console.log("account" + JSON.stringify(this.state.loggedAccount));
         });
        }
    })
    .catch(err => Alert.alert(
      "UrbanRider",
      "Please Login Again",
      [{ text: "OK", onPress: () => this.facebookLogin() }],
      { cancelable: false }
      )
    )
  }
```
![Screenshot_20190403-155743](https://user-images.githubusercontent.com/43109103/55529319-6d5b8480-56be-11e9-8944-7fc2274fdb8f.png)

**Comment by jpgarcia** [comment] 2019-07-01 03:40
We couldn't reproduce this issue. If you are still facing the issue please provide a public repo with the code to be able to reproduce it.

Closing it for now.

**Closed by jpgarcia** 2019-07-01 03:40 UTC
