### ISSUE TITLE
Example RN040 not working

### ISSUE THREAD

**Issue by mauriciocoelho** [underscopeio/react-native-facebook-account-kit#62] opened 2017-02-16 19:15 UTC
### Issue Description

Hello, i'm try to run the example and not work :(

### Steps to Reproduce / Code Snippets

i try RN033 and RN040 following this steps

```
git clone https://github.com/underscopeio/react-native-facebook-account-kit
cd react-native-facebook-account-kit/examples/RN040
npm install
react-native run-ios
```
and both returned the same error:

![screen shot 2017-02-16 at 17 10 34](https://cloud.githubusercontent.com/assets/5712300/23036771/2fa35aa8-f46b-11e6-840c-d0b12b8e70c1.png)

#### Expected Results

run app

### Additional Information

* React Native version: 0.40.0
* Platform(s): iOS

**Comment by gaguirre** [comment] 2017-02-22 13:13
Hi @mauriciocoelho, based on the error message it's related to the `Camera` module.
I'll close the issue, please reopen if it's caused by this module.

**Closed by gaguirre** 2017-02-22 13:13 UTC
