### ISSUE TITLE
Calling RNAccountkit.loginWithPhone() triggers Accountkit UI but doesn't call function passed into `.then()` after successful verification.

### ISSUE THREAD

**Issue by asyrique** [underscopeio/react-native-facebook-account-kit#104] opened 2017-10-26 12:25 UTC
### Issue Description

Calling `RNAccountkit.loginWithPhone()` shows the Accountkit UI, but does not call the function in `.then(code => {...})`. Neither does it error out and call the `.catch()`

### Steps to Reproduce / Code Snippets

```
import RNAccountkit from 'react-native-facebook-account-kit'
...
accountKit(input){
  RNAccountKit.configure({
    responseType: 'code',
    initialPhoneCountryPrefix: '+' + input.substring(0,3),
    initialPhoneNumber: input.substring(3)
  })
  console.log("Logging in with phone")
  RNAccountKit.loginWithPhone()
    .then(code => {
      console.log(code)
    })
    .catch(err => console.log(err))
  console.log("Finished") 
}
...
render(){
  return (
    <TouchableOpacity onPress={e => this.accountkit("+1234567890")} />
  )
}
```

#### Expected Results

Accountkit UI pops up, SMS is sent and verified, and then `.then()` is called to pass the control flow on.

Expected console logs:
- Logging in with phone
- [Accountkit pops up, SMS is sent and verified]
- "Finished"
- "[code from FB here]" OR "Error (caught by catch)"

Actual console.logs:
- Logging in with phone
- [Accountkit pops up, SMS is sent and verified]
- [Nothing else. Not even "Finished"]

### Additional Information

* React Native Account Kit version: 0.9.0
* React Native version: 0.48 (Expokit 21.0.0)
* Platform(s) (iOS, Android, or both?): Android (haven't managed to test iOS yet)

**Comment by chileung69** [comment] 2017-12-19 03:48
Seem the catch missing something, should be:
.catch((err) => console.log(err))

**Comment by priezz** [comment] 2018-01-19 04:06
I have the same behavior (Android, RN 0.51). Is there any solution?

**Comment by gaguirre** [comment] 2018-01-23 13:17
It seems like the library was not linked properly. Take a look to your `build.gradle`, `settings.gradle` and `MainApplication.java` and see they were properly modified when running `react-native link`.
@asyrique @priezz

**Comment by priezz** [comment] 2018-01-24 09:17
@gaguirre, what do you mean by "not properly"? As I understand, there are just two options - linked or not :) In my case it is linked, because all other functions work as documented and execute callbacks. I already have the workaround to use the module w/o the callback execution, but if it would work as documented it would be much better.

**Comment by priezz** [comment] 2018-01-24 09:29
The workaround mentioned:

```
export default class Stats extends React.PureComponent<any> {
    componentDidMount() {
        AccountKit.configure({
            facebookNotificationsEnabled: true,
            receiveSMS: true,
            readPhoneStateEnabled: true,
            responseType: 'token',
            titleType: 'login',
            theme: { 
                // ... 
            },
        })
    }

    async checkAccount() {
        try {
            if(!await AccountKit.getCurrentAccount()) return
            const tokenData = await AccountKit.getCurrentAccessToken()
            if(tokenData) {
                // ... Do some staff here
            }
        } catch(e) {
            console.log('Login/checkAccount()', e.message)
        }
    }

    returndFromAccountKitHandler = async (nextState: string) => {
        if(nextState !== 'active') return
        AppState.removeEventListener('change', this.returndFromAccountKitHandler)
        this.checkAccount()
    }

    loginWithPhone = () => {
        AppState.addEventListener('change', this.returndFromAccountKitHandler)
        AccountKit.loginWithPhone().catch((e: any) => console.log('Login', e))
    }
    loginWithEmail = () => {
        AppState.addEventListener('change', this.returndFromAccountKitHandler)
        AccountKit.loginWithEmail().catch((e: any) => console.log('Login', e))
    }

    render() {
        return <View>
            <BlueButton text="SIGN IN WITH PHONE NUMBER" onPress={this.loginWithPhone} />
            <Button text="SIGN IN WITH EMAIL" onPress={this.loginWithEmail} />
        </View>
    }
}
```

**Comment by billel-boudchicha** [comment] 2018-06-30 18:04
Hi @priezz thanks for "The workaround " , i think AppState doesn't behave the same in android and ios
it doesn't fire in ios simulator but works as expected in android simulator 6,
React Native Account Kit version: 0.9.3
React Native version: 0.55.4

Did you came up with a better solution thank you

**Comment by priezz** [comment] 2018-08-16 23:33
@billel-boudchicha For Android I track `AppState` changes, for iOS AccountKit callback works as expected. So just do `if(Platform.OS === 'android')` checking, when calling `AppState.addEventListener` and `AppState.removeEventListener`

**Comment by jpgarcia** [comment] 2019-07-01 04:12
Guys I couldn't reproduce the issue with the latest version **1.2.0** we released today. 

I'll close this issue for now. If you continue facing the issue please re-open this one but It would be great if you can provide a public Github repo example to be able to troubleshoot the issue.

Thanks!

**Closed by jpgarcia** 2019-07-01 04:12 UTC
