### ISSUE TITLE
Android dependency 'com.android.support:support-v4' has different version for the compile (27.0.2)

### ISSUE THREAD

**Issue by crsgarcias** [underscopeio/react-native-facebook-account-kit#176] opened 2019-02-13 18:42 UTC
I was running the example RN0577 and its ok, but in my project not working. I have react-native react-native-fbsdk too.

The error is:

```
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (27.0.2) and runtime (27.1.1) classpath. You should manually set the s
ame version via DependencyResolution
```

My package.json is:
```
{
  "name": "project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "adm-zip": "^0.4.13",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "plist": "^3.0.1",
    "proptypes": "^1.1.0",
    "react": "^16.6.1",
    "react-native": "^0.57.7",
    "react-native-admob": "^2.0.0-beta.5",
    "react-native-contacts": "^2.2.4",
    "react-native-elements": "^0.19.1",
    "react-native-facebook-account-kit": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-zoom-viewer": "^2.2.23",
    "react-native-paper": "^1.11.0",
    "react-native-share": "^1.1.3",
    "react-native-smart-splash-screen": "^2.3.5",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^2.9.2",
    "react-navigation-redux-helpers": "^2.0.6",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "styled-components": "^3.4.2",
    "xcode": "^2.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.4.1",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by phanbien9x** [comment] 2019-02-19 08:35
Did you find a solution @crsgarcias. I have the same problem!

**Comment by jpgarcia** [comment] 2019-02-19 09:59
can you guys create a public repo with a simple project so we can reproduce and troubleshoot the issue?

**Comment by tmjordan** [comment] 2019-02-19 10:04
@phanbien9x , try to add these lines in your android/app/build.gradle dependencies
```
implementation ("com.android.support:support-v4:${rootProject.ext.supportLibVersion}")
implementation ("com.android.support:design:${rootProject.ext.supportLibVersion}")
```

**Comment by phanbien9x** [comment] 2019-02-19 10:48
@tmjordan after add these line, clear bundle, delete node_modules, run: npm install. And try to build the app many time and it worked. But now my app crash. Build Successful but why? @jpgarcia. I will put a repo.

**Comment by phanbien9x** [comment] 2019-02-19 14:49
My repo: https://github.com/phanbien9x/Test_AK . Please tell me for the result of this. Grateful thanks!

**Comment by tmjordan** [comment] 2019-02-19 15:01
@phanbien9x, try this:
```
    implementation project(':react-native-fcm')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-fbsdk')
	
	implementation(project(':react-native-facebook-account-kit')){
		exclude group: 'com.facebook.android', module: 'account-kit-sdk'
	}
	implementation ('com.facebook.android:account-kit-sdk:4.+') {
		exclude group: 'com.google.android.gms', module: 'play-services-auth-api-phone'
		exclude group: 'com.google.android.gms', module: 'play-services-auth'
	}
	implementation 'com.google.android.gms:play-services-base:16+'
	implementation 'com.google.android.gms:play-services-auth-api-phone:16.+'
	implementation 'com.google.android.gms:play-services-auth:16.+'

	implementation ("com.android.support:support-v4:${rootProject.ext.supportLibVersion}")
	implementation ("com.android.support:design:${rootProject.ext.supportLibVersion}")
	
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
```

**Comment by tmjordan** [comment] 2019-02-19 15:02
@phanbien9x, try this:
```
implementation project(':react-native-fcm')
implementation project(':react-native-image-picker')
implementation project(':react-native-vector-icons')
implementation project(':react-native-gesture-handler')
implementation project(':react-native-fbsdk')

implementation(project(':react-native-facebook-account-kit')){
	exclude group: 'com.facebook.android', module: 'account-kit-sdk'
}
implementation ('com.facebook.android:account-kit-sdk:4.+') {
	exclude group: 'com.google.android.gms', module: 'play-services-auth-api-phone'
	exclude group: 'com.google.android.gms', module: 'play-services-auth'
}
implementation 'com.google.android.gms:play-services-base:16+'
implementation 'com.google.android.gms:play-services-auth-api-phone:16.+'
implementation 'com.google.android.gms:play-services-auth:16.+'

implementation ("com.android.support:support-v4:${rootProject.ext.supportLibVersion}")
implementation ("com.android.support:design:${rootProject.ext.supportLibVersion}")

implementation fileTree(dir: "libs", include: ["*.jar"])
implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
implementation "com.facebook.react:react-native:+"  // From node_modules
```

**Comment by phanbien9x** [comment] 2019-02-19 16:38
I changed my build.gradle like your recomend
```
    implementation project(':react-native-fcm')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-fbsdk')
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation(project(':react-native-facebook-account-kit')){
	    exclude group: 'com.facebook.android', module: 'account-kit-sdk'
    }
    implementation ('com.facebook.android:account-kit-sdk:4.+') {
	    exclude group: 'com.google.android.gms', module: 'play-services-auth-api-phone'
	    exclude group: 'com.google.android.gms', module: 'play-services-auth'
    }
    implementation 'com.google.android.gms:play-services-base:16+'
    implementation 'com.google.android.gms:play-services-auth-api-phone:16.+'
    implementation 'com.google.android.gms:play-services-auth:16.+'

    implementation ("com.android.support:support-v4:${rootProject.ext.supportLibVersion}")
    implementation ("com.android.support:design:${rootProject.ext.supportLibVersion}")

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
```
But the app still crash. Sad!

**Comment by tmjordan** [comment] 2019-02-19 16:46
@phanbien9x at what time does it crash?

**Comment by phanbien9x** [comment] 2019-02-20 01:12
@tmjordan At the start after build successful!.  I waste a day for this error. Is it happen when my sdk is to                                        old? I will update the sdk packager hope this help.

**Comment by crsgarcias** [comment] 2019-02-20 02:37
@phanbien9x  yes I can fix the error! the problem was react native admob and I setted the configurations that @tmjordan said me

**Comment by phanbien9x** [comment] 2019-02-20 02:55
@crsgarcias Did you fix this?

**Comment by jpgarcia** [comment] 2019-02-20 03:00
I'll close this issue since it is not related to the library itself but related to some specific compatibility configuration. In any case you can still discussing around it here in case someone face the same issue

**Closed by jpgarcia** 2019-02-20 03:00 UTC

**Comment by phanbien9x** [comment] 2019-02-20 09:16
After update sdk jdk, android studio, android 9 (Api Level 28), update newest react native project. It finally not crashing again. So long day! -_

**Comment by phanbien9x** [comment] 2019-02-20 09:24
Thank you @tmjordan for helping me! Your recommend is usefull.

**Comment by crsgarcias** [comment] 2019-02-20 13:11
@phanbien9x you did it! jaja

**Comment by phanbien9x** [comment] 2019-02-21 07:39
No. It still not work. It only work when i run it in new project. But when I run in my project nothing change. I'm trying to make it work! -_

**Comment by phanbien9x** [comment] 2019-02-21 08:19
AccountKit.loginWithPhone = undefined. Why it happen ?

**Comment by phanbien9x** [comment] 2019-02-21 12:56
For someone like me use firebase of fcm with this package.
Change "react-native-facebook-account-kit": "^0.11.0",
And add implementation "com.android.support:design:27.1.0" -- Not another version! I checked.
And it work. Hope it help!

**Comment by jpgarcia** [comment] 2019-02-21 15:35
@phanbien9x did you check my suggestion here => https://github.com/underscopeio/react-native-facebook-account-kit/issues/157#issuecomment-423949726

**Comment by phanbien9x** [comment] 2019-02-22 04:03
@jpgarcia I will check and show you the result.

**Comment by phanbien9x** [comment] 2019-02-22 08:10
@jpgarcia FCM build.gradle here. How can i force dependencies. I try to add your code to the end of file but nothing happens.
https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle
